# Site Configs

# url: http://blog.geuer-pollmann.de/
url: ""


name: Dr Christian Geuer-Pollmann
author: Dr Christian Geuer-Pollmann
sitetitle: Christian Geuer-Pollmann's Blog
description: Christian Geuer-Pollmann's Blog
twittername: chgeuer

safe: true
lsi: false
encoding: UTF-8
markdown: redcarpet
markdown_ext:  md,markdown
pygments: true
set :markdown, fenced_code_blocks: true

# Pagination
paginate: 2
relative_permalinks: true
blogurl:       "/blog"
blogpageprefix: "/blog/page"
paginate_path: "/blog/page:num"
permalink:     "/blog/:year/:month/:day/:title/"
