# Site Configs
safe: true
lsi: false
encoding: UTF-8

name: Dr Christian Geuer-Pollmann
description: Christian Geuer-Pollmann's Blog
# url: http://blog.geuer-pollmann.de/
url: ""
markdown: redcarpet
markdown_ext:  md,markdown
pygments: true
permalink: /blog/:year/:month/:day/:title/

paginate: 5
paginate_path: "/blog/page:num"


set :markdown, fenced_code_blocks: true
