# Site Configs

# url: http://blog.geuer-pollmann.de/
url: ""


name: Dr Christian Geuer-Pollmann
author: Dr Christian Geuer-Pollmann
sitetitle: Christian Geuer-Pollmann's Blog
description: Christian Geuer-Pollmann's Blog
twittername: chgeuer
twitterwidgetid: 310063674322731008

# 
# Themes from http://bootswatch.com/
# amelia, cerulean, cosmo, cyborg, flatly, journal, readable, simplex, slate, spacelab, united, yeti
#
bootswatchtheme: "yeti"

safe: true
encoding: UTF-8
markdown_ext:  md,markdown
set :markdown, fenced_code_blocks: true
markdown:    markdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"





# Pagination
paginate: 2
relative_permalinks: true
blogurl:       "/blog"
blogpageprefix: "/blog/page"
paginate_path: "/blog/page:num"
permalink:     "/blog/:year/:month/:day/:title/"



# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
